### PR TITLE
Update VS Code to 1.57.1

### PR DESCRIPTION
**Pull request by jacobgkau**
See https://github.com/pop-os/pop/issues/1741.

### CODE REVIEW

**Review by leviport — APPROVED** [review]
CI doesn't build this repo, but URLs, checksums, and version numbers all seem to be correct.

**Comment by jacobgkau** [comment]
Before merging this, I think it would be a good idea to understand why https://github.com/pop-os/vscode was created. It seems like it shouldn't have been, since we were providing this package via repo-proprietary, but I assume there was a reason. Either way, it would need to be removed for this package to have any effect, since the PPA is pinned and the proprietary repo isn't.

**Review by jackpot51 — APPROVED** [review]

**Comment by jackpot51** [comment]
@mmstick can you answer @jacobgkau's question?

**Comment by mmstick** [comment]
The reason was so that the proprietary PPA wouldn't have to be regenerated for every VS Code update.

**Pull request merged**
