### PR TITLE
Update signal to 1.40.1

### PR DESCRIPTION
**Pull request by waja**
I used 2 commits, just in case don't want to include it into newer releases.

### CODE REVIEW

**Comment by jacobgkau** [comment]
Signal is [transitioned to Flatpak](https://github.com/pop-os/transition) on current releases of Pop, and is no longer included in this repo intentionally.

If you remove the second commit, then I don't see why we can't push the updated version on Bionic; we're currently only supporting Focal and Groovy, but Bionic is technically still being supported by Ubuntu.

**Comment by waja** [comment]
As you wished... :)

Anyway ... those flatpak transition is breaking my heart. :(

**Comment by jacobgkau** [comment]
> Anyway ... those flatpak transition is breaking my heart. :(

For what it's worth, we are only transitioning apps that we've determined to be feature-complete in their Flatpak implementations. For example, Discord is available through Flathub, but we continue to maintain that package as a .deb because the Flatpak version has limitations with drag-and-drop file attachments and game integrations.

When other teams are already maintaining perfectly usable Flatpak packages for third-party apps, time and effort by the Pop!_OS engineers is better spent working on Pop-specific features/applications and on supporting the upstream first-party projects that we rely on, rather than duplicating effort repackaging specific third-party apps. (We initially started packaging these apps because they were not easy to install on Pop!_OS, but Flatpak has solved that problem and done it in a way that also benefits other distributions.)

**Comment by waja** [comment]
While I see you point, installing everything (selfcontained) in a flatpack image, it is very bloated compared to a debian package solution and sometimes more hassle to use the application (filesystem mapping etc).

**Comment by jacobgkau** [comment]
If you're opposed to Flatpak on technical grounds, using Signal's own apt repository is still an option: https://signal.org/download/ 

Using their repo will also mean you get updates directly from them instead of having to wait for us to bump the version in this repo every time they make an update.

**Review by jacobgkau — APPROVED** [review]
Confirmed that the new Signal version (1.40.1) builds and installs/functions on a Bionic system. Upon upgrading the system to Focal, I am still prompted to transition to Flatpak, and the transition completes as expected.

**Pull request merged**
