### PR TITLE
Update to Discord 0.0.42

### PR DESCRIPTION
**Pull request by OverkillGuy**

### CODE REVIEW

**Comment by gabriele2000** [comment]
What the hell happened to discord integrated updater?
Has it become useless or what?

Incompetent devs.

**Comment by OverkillGuy** [comment]
> What the hell happened to discord integrated updater? Has it become useless or what?

You're still free to use the discord UI's "Download" button to download the updated debian package, and proceed with the update manually. It's just that the package will come from raw download not a proper PPA source like this one.

This PR repackages the deb file from upstream into a PPA, so that you don't _have_ to do that, just wait for the update from `apt upgrade`.

>  Incompetent devs.

Please, the Pop_OS! build team has been pretty responsive to these PRs (and I've done quite a few, look at the repo history), no need to be mean to them, they are making the best of a flimsy external dependency, and won't be faster to merge updates when treated badly. 

Let's stay positive here, say it with me: "Discord got an update, yey! just need Pop to catch up to it! Let's go!"

**Comment by gabriele2000** [comment]
> > What the hell happened to discord integrated updater? Has it become useless or what?
> 
> You're still free to use the discord UI's "Download" button to download the updated debian package, and proceed with the update manually. It's just that the package will come from raw download not a proper PPA source like this one.
> 

If I say "integrated updater" it's pretty clear I mean the thing that says "checking updates... downloading updates"

> 
> > Incompetent devs.
> 
> Please, the Pop_OS! build team has been pretty responsive to these PRs (and I've done quite a few, look at the repo history), no need to be mean to them, they are making the best of a flimsy external dependency, and won't be faster to merge updates when treated badly.

I won't EVER be mean to System_76, I'm a fan of them and I wasn't insulting them.

I was insulting Discord devs of whoever decided to release a "major" update every week, with one bug fixed or something like that.

> Let's stay positive here, say it with me: "Discord got an update, yey! just need Pop to catch up to it! Let's go!"

No.
Updates like that were for big things, for everything else there was the **integrated updater**, which is that little thing that opens before Discord UI.
I bet you've noticed it everytime.

That little thing was important as hell because for big updates you had to download the installer again (rarely) because Discord just got a big update.
The updater was for 90% of the cases.

**Comment by leviport** [comment]
Let's keep this about the pull request, shall we? :slightly_smiling_face:

**Comment by jacobgkau** [comment]
@gabriele2000 Yes, Discord's kind of an odd case, and it's not optimal for distributors. It's 90% a web app, but sometimes (and recently, increasingly often) they update the Electron wrapper. When they push updates that are only to the web app portion, you'll see the integrated updater download some things, then the app will launch. When they decide to push an update to the actual wrapper/app, their integrated updater locks everyone out of being able to launch until they update to the latest version (even though they're not that strict when it comes to running in a normal web browser; I've never seen Discord fail to run in Firefox or Chromium because my browser was outdated).

I thought Discord had a repo you could add if you wanted to get package updates directly from them, but it looks like they don't: https://support.discord.com/hc/en-us/community/posts/360031737491-Give-us-an-apt-repository-Linux Still, you're welcome to download and install the .deb directly from Discord if you ever don't want to wait for us to push one out via the Pop!_OS repos.

**Review by jacobgkau — APPROVED** [review]
New checksum is correct.

**Comment by jacobgkau** [comment]
This has been released.

**Comment by gabriele2000** [comment]
> if you ever don't want to wait for us to push one out via the Pop!_OS repos.

Nah, it's just annoying seeing this increasingly often.

**Comment by OverkillGuy** [comment]
Sorry @gabriele2000 for assuming your comment was low-context dump on Pop, I should have read your message more fully.

**Comment by gabriele2000** [comment]
> Sorry @gabriele2000 for assuming your comment was low-context dump on Pop, I should have read your message more fully.

Nah man, don't worry about it... instead I should say sorry for my tone, I was beyond pissed for the fact that I'm updating discord about every two days and the internal updater (which was always used) isn't used, except for those two times a year.

**Pull request merged**
