### PR TITLE
Merge curated-free repo & Update to multi-suite config

### LINKED ISSUE #3: Add a readme and license

### PR DESCRIPTION
**Pull request by mmstick**
- Migrates the free software entries to [repo-curated-free](https://github.com/pop-os/repo-curated-free)
- Imports updated versions of `kicad` and `freecad` from their repos
- Imports updated versions of `thunderbird`, and `firefox-esr`, from the mozillateam PPA
- Backports `rustc 1.28.0` from cosmic for bionic.
- Adds license and readme

Should we also add updated versions of Scribus, GIMP, MPV, etc.?

Requires https://github.com/pop-os/debrepbuild/pull/25
Closes #3

### CODE REVIEW

**Comment by brs17** [comment]
Not much for me to test here (now). I would say we can always add updated versions of other programs at another point, I don't see that as holding off from merging this. 

I see you add a README, since you're moving free apps to repo-curated-free, is there a reason you mention:
```
Currently, this repo also includes free software as well, for convenience &
inclusion in Pop!\_OS by default for those on 18.04.
```
?

**Comment by mmstick** [comment]
@brs17 The definitions for fetching the free software comes from the curated-free repo, but that repo gets merged here when building so it also includes that repo.

**Comment by brs17** [comment]
I approved, @jackpot51 you should probably actually take a look to make sure nothing seems out of the ordinary.

**Comment by mmstick** [comment]
Also not authorized on this one.

**Comment by jackpot51** [comment]
@mmstick you are auth'd now

**Pull request merged**
